# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nNrgMZM5vrdmD7At6S8fRrgO-QLIsnS
"""

import streamlit as st
import tensorflow as tf
import pickle
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load model and tokenizer
model = tf.keras.models.load_model("Anu_DL.h5", compile=False)
with open("tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

st.title("Spam Detector")
st.write("Enter your email content below:")

email_input = st.text_area("Email text", height=200)

if st.button("Predict"):
    if email_input.strip() == "":
        st.warning("Please enter an email message.")
    else:
        # Preprocess input
        seq = tokenizer.texts_to_sequences([email_input])
        padded = pad_sequences(seq, maxlen=100)
        pred = model.predict(padded)[0][0]

        if pred > 0.5:
            st.error(f"SPAM (Confidence: {pred:.2f})")
        else:
            st.success(f"NOT SPAM (Confidence: {1 - pred:.2f})")